appId: com.m1ku.turn
name: Settings
---
- launchApp:
    clearState: true
- extendedWaitUntil:
    visible: Listen
    timeout: 30000
- waitForAnimationToEnd
- tapOn: Settings
- extendedWaitUntil:
    visible: Your words
    timeout: 10000
- waitForAnimationToEnd
- takeScreenshot: settings-top
- scrollUntilVisible:
    element: Erase all data
- takeScreenshot: settings-bottom
